// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/artists.ts";
import * as $4 from "./routes/api/arts.ts";
import * as $5 from "./routes/api/collection.ts";
import * as $6 from "./routes/art/[slug].tsx";
import * as $7 from "./routes/artists.tsx";
import * as $8 from "./routes/arts.tsx";
import * as $9 from "./routes/bg.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/indicators.tsx";
import * as $12 from "./routes/mouvement/[slug].tsx";
import * as $13 from "./routes/mouvements.tsx";
import * as $$0 from "./islands/ArtistsSearch.tsx";
import * as $$1 from "./islands/ArtsSearch.tsx";
import * as $$2 from "./islands/CollectionSearch.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/Doughnut.tsx";
import * as $$5 from "./islands/Footer.tsx";
import * as $$6 from "./islands/Nav.tsx";
import * as $$7 from "./islands/PolarArea.tsx";
import * as $$8 from "./islands/WaterDrop.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/artists.ts": $3,
    "./routes/api/arts.ts": $4,
    "./routes/api/collection.ts": $5,
    "./routes/art/[slug].tsx": $6,
    "./routes/artists.tsx": $7,
    "./routes/arts.tsx": $8,
    "./routes/bg.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/indicators.tsx": $11,
    "./routes/mouvement/[slug].tsx": $12,
    "./routes/mouvements.tsx": $13,
  },
  islands: {
    "./islands/ArtistsSearch.tsx": $$0,
    "./islands/ArtsSearch.tsx": $$1,
    "./islands/CollectionSearch.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/Doughnut.tsx": $$4,
    "./islands/Footer.tsx": $$5,
    "./islands/Nav.tsx": $$6,
    "./islands/PolarArea.tsx": $$7,
    "./islands/WaterDrop.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
