// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/artists.ts";
import * as $4 from "./routes/api/arts.ts";
import * as $5 from "./routes/api/collection.ts";
import * as $6 from "./routes/art/[slug].tsx";
import * as $7 from "./routes/artists.tsx";
import * as $8 from "./routes/arts.tsx";
import * as $9 from "./routes/background/gray.tsx";
import * as $10 from "./routes/background/white.tsx";
import * as $11 from "./routes/histocharacters.tsx";
import * as $12 from "./routes/index.tsx";
import * as $13 from "./routes/indicators.tsx";
import * as $14 from "./routes/movement/[slug].tsx";
import * as $15 from "./routes/movements.tsx";
import * as $16 from "./routes/women.tsx";
import * as $$0 from "./islands/Quote.tsx";
import * as $$1 from "./islands/chart/Doughnut.tsx";
import * as $$2 from "./islands/chart/PolarArea.tsx";
import * as $$3 from "./islands/footer/Footer.tsx";
import * as $$4 from "./islands/footer/WaterDrop.tsx";
import * as $$5 from "./islands/header/Nav.tsx";
import * as $$6 from "./islands/layout/ArtistsLayout.tsx";
import * as $$7 from "./islands/layout/ArtsLayout.tsx";
import * as $$8 from "./islands/livesearch/ArtistsSearch.tsx";
import * as $$9 from "./islands/livesearch/ArtsSearch.tsx";
import * as $$10 from "./islands/livesearch/CollectionSearch.tsx";
import * as $$11 from "./islands/livesearch/HistoSearch.tsx";
import * as $$12 from "./islands/livesearch/WomenSearch.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/artists.ts": $3,
    "./routes/api/arts.ts": $4,
    "./routes/api/collection.ts": $5,
    "./routes/art/[slug].tsx": $6,
    "./routes/artists.tsx": $7,
    "./routes/arts.tsx": $8,
    "./routes/background/gray.tsx": $9,
    "./routes/background/white.tsx": $10,
    "./routes/histocharacters.tsx": $11,
    "./routes/index.tsx": $12,
    "./routes/indicators.tsx": $13,
    "./routes/movement/[slug].tsx": $14,
    "./routes/movements.tsx": $15,
    "./routes/women.tsx": $16,
  },
  islands: {
    "./islands/Quote.tsx": $$0,
    "./islands/chart/Doughnut.tsx": $$1,
    "./islands/chart/PolarArea.tsx": $$2,
    "./islands/footer/Footer.tsx": $$3,
    "./islands/footer/WaterDrop.tsx": $$4,
    "./islands/header/Nav.tsx": $$5,
    "./islands/layout/ArtistsLayout.tsx": $$6,
    "./islands/layout/ArtsLayout.tsx": $$7,
    "./islands/livesearch/ArtistsSearch.tsx": $$8,
    "./islands/livesearch/ArtsSearch.tsx": $$9,
    "./islands/livesearch/CollectionSearch.tsx": $$10,
    "./islands/livesearch/HistoSearch.tsx": $$11,
    "./islands/livesearch/WomenSearch.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
