export const colorScheme = {
  everblush: {
    dark: "#141b1e",
    lighterdark: "#232a2d",
    red: "#e57474",
    green: "#8ccf7e",
    yellow: "#e5c76b",
    blue: "#67b0e8",
    magenta: "#c47fd5",
    cyan: "#6cbfbf",
    gray: "#b3b9b8",
    white: "#dadada",
  },
};

export const currentColorScheme = "everblush";

export const extraColors = {
  water: "#e0f7fa",
};

// Pour la carte du Monde
export const worldColors = [
  "#000000", // Allemagne (noir)
  "#FF0000", // Armenia (rouge)
  "#FF0000", // Arménie (rouge)
  "#ED2939", // Austria (rouge autrichien)
  "#ED2939", // Autriche (rouge autrichien)
  "#00662E", // Belarus (vert)
  "#000000", // Belgique (noir)
  "#000000", // Belgium (noir)
  "#00662E", // Biélorussie (vert)
  "#FF0000", // Canada (rouge)
  "#DE2910", // Chine (rouge chinois)
  "#FCD116", // Colombia (jaune)
  "#FCD116", // Colombie (jaune)
  "#171796", // Croatia (bleu croate)
  "#171796", // Croatie (bleu croate)
  "#FFFFFF", // Czechoslovakia (blanc)
  "#C60C30", // Danemark (rouge danois)
  "#C60C30", // Denmark (rouge danois)
  "#FFC400", // Espagne (jaune)
  "#0072CE", // Estonia (bleu estonien)
  "#0072CE", // Estonie (bleu estonien)
  "#B22234", // États-Unis d'Amérique (Old Glory Red)
  "#003580", // Finland (bleu finlandais)
  "#003580", // Finlande (bleu finlandais)
  "#0055A4", // France (bleu français)
  "#000000", // Germany (noir)
  "#0D5EAF", // Grèce (bleu grec)
  "#0D5EAF", // Greece (bleu grec)
  "#CE1126", // Hongrie (rouge hongrois)
  "#CE1126", // Hungary (rouge hongrois)
  "#009246", // Italie (vert italien)
  "#009246", // Italy (vert italien)
  "#BC002D", // Japan (rouge japonais)
  "#BC002D", // Japon (rouge japonais)
  "#006847", // Mexico (vert mexicain)
  "#006847", // Mexique (vert mexicain)
  "#00AEEF", // Monde (bleu « Terre »)
  "#AE1C28", // Netherlands (rouge néerlandais)
  "#BA0C2F", // Norvège (rouge norvégien)
  "#BA0C2F", // Norway (rouge norvégien)
  "#AE1C28", // Pays-Bas (rouge néerlandais)
  "#DE2910", // People's Republic of China (rouge chinois)
  "#FFFFFF", // Poland (blanc)
  "#FFFFFF", // Pologne (blanc)
  "#FF0000", // Portugal (rouge portugais)
  "#012169", // Royaume-Uni (bleu Union Jack)
  "#FFFFFF", // Russian Federation (blanc)
  "#FFFFFF", // Russie (blanc)
  "#005DA4", // Slovenia (bleu slovène)
  "#005DA4", // Slovénie (bleu slovène)
  "#FFC400", // Spain (jaune)
  "#005BBB", // Suède (bleu suédois)
  "#FF0000", // Suisse (rouge)
  "#005BBB", // Sweden (bleu suédois)
  "#FF0000", // Switzerland (rouge)
  "#FFFFFF", // Tchécoslovaquie (blanc)
  "#E30A17", // Turkey (rouge turc)
  "#E30A17", // Turquie (rouge turc)
  "#0057B8", // Ukraine (bleu ukrainien)
  "#012169", // United Kingdom (bleu Union Jack)
  "#B22234", // United States of America (Old Glory Red)
  "#DA251D", // Vietnam (rouge vietnamien)
];

export const tagColorsEN = [
  "#7F7F7F", // Abstract (conceptual gray)
  "#D2B48C", // Algeria (tan oriental)
  "#DAA520", // Allegory (antique gold)
  "#C19A6B", // Animals (light sandy brown)
  "#A0A0A0", // Architecture (architectural gray)
  "#DC143C", // Asian Art (Asian crimson)
  "#FF69B4", // Dance (flamingo pink)
  "#000000", // Death (black)
  "#FFD700", // Drawing (golden yellow)
  "#87CEFA", // Dream (soft sky blue)
  "#CE1126", // Egypt (Egyptian red)
  "#800080", // Fantasy (imaginary purple)
  "#FF4500", // Fire (fire orange)
  "#FF69B4", // Flowers (vivid floral pink)
  "#66CDAA", // French Polynesia (tropical turquoise)
  "#FFD700", // Gold (pure gold)
  "#6B8E23", // History (dark olive green)
  "#FF9933", // India (Indian saffron)
  "#708090", // Industry (slate gray)
  "#F4A460", // Interior (warm sand)
  "#4169E1", // Israel (royal Israeli blue)
  "#228B22", // Landscape (forest green)
  "#FF1493", // Love (passionate pink)
  "#9370DB", // Monarchy (monarchic violet)
  "#A0522D", // Mountains (rock brown)
  "#DA70D6", // Music (melodic light purple)
  "#B22222", // Mythology (ancient red)
  "#2E8B57", // Nature (natural green)
  "#FFC0CB", // Nude (flesh pink)
  "#F5DEB3", // Portrait (flesh beige)
  "#D2691E", // Religion (mystic brown)
  "#6495ED", // Science (electric blue)
  "#1E90FF", // Sea (ocean blue)
  "#90EE90", // Self-portrait (light green)
  "#CD853F", // Still Life (classic brown)
  "#00CED1", // Time (turquoise)
  "#4682B4", // Transport (steel blue)
  "#B8860B", // Trompe-l'oeil (illusionist ochre)
  "#778899", // Urban (concrete gray)
  "#8B4513", // Walnut Ink (walnut husk brown)
  "#8B0000", // War (dark red)
  "#00BFFF", // Weather (sky blue)
];

export const tagColorsFR = [
  "#7F7F7F", // Abstrait (gris conceptuel)
  "#D2B48C", // Algérie (brun oriental)
  "#DAA520", // Allégorie (doré antique)
  "#FF1493", // Amour (rose passion)
  "#C19A6B", // Animaux (brun sable clair)
  "#A0A0A0", // Architecture (gris architectural)
  "#DC143C", // Art asiatique (cramoisi asiatique)
  "#C71585", // Autoportrait (rose pourpre profond)
  "#8B4513", // Brou de noix (brun brou de noix)
  "#FF69B4", // Danse (rose flamant)
  "#FFD700", // Dessin (jaune doré artistique)
  "#800080", // Fantastique (violet imaginaire)
  "#FF4500", // Feu (orange feu)
  "#FF69B4", // Fleurs (rose vif floral)
  "#8B0000", // Guerre (rouge sombre)
  "#6B8E23", // Histoire (vert olive foncé)
  "#FF9933", // Inde (orange safran indien)
  "#708090", // Industrie (gris ardoise)
  "#F4A460", // Intérieur (sable chaud)
  "#4169E1", // Israël (bleu royal israélien)
  "#00CED1", // Le temps (turquoise)
  "#1E90FF", // Mer (bleu océan)
  "#9370DB", // Monarchie (violet monarchique)
  "#A0522D", // Montagnes (brun roche)
  "#000000", // Mort (noir)
  "#DA70D6", // Musique (violet clair mélodique)
  "#B22222", // Mythologie (rouge antique)
  "#2E8B57", // Nature (vert nature)
  "#CD853F", // Nature morte (brun clair classique)
  "#FFC0CB", // Nu (rose chair)
  "#FFD700", // Or (or pur)
  "#228B22", // Paysage (vert forêt)
  "#66CDAA", // Polynésie française (turquoise tropical)
  "#F5DEB3", // Portrait (beige peau)
  "#D2691E", // Religion (brun mystique)
  "#87CEFA", // Rêve (bleu ciel doux)
  "#6495ED", // Science (bleu électrique)
  "#00BFFF", // Temps (bleu ciel)
  "#4682B4", // Transport (bleu acier)
  "#B8860B", // Trompe-l'œil (jaune ocre illusionniste)
  "#778899", // Urbain (gris béton)
  "#CE1126", // Égypte (rouge égyptien)
];
