export const quotes = [
  "“J'avais pour les étables un goût plus irrésistible que jamais courtisan pour les antichambres royales ou impériales.” —Rosa Bonheur",
  "“Une œuvre d'art qui n'a pas commencé dans l'émotion n'est pas de l'art.” —Paul Cézanne",
  "“Si toute vie va inévitablement vers sa fin, nous devons, durant la nôtre, la colorier avec nos couleurs d'amour et d'espoir.” —Marc Chagall",
  "“La peinture est la face visible de l’iceberg de ma pensée.” —Salvador Dalí",
  "“Mon but : ne copie jamais. Crée un nouveau style, clair, des couleurs lumineuses, et perçois l’élégance dans tes modèles.” —Tamara de Lempicka",
  "“Le peintre doit s’efforcer d’être universel.” —Léonard de Vinci",
  "“Le premier mérite d’un tableau est d’être une fête pour l’œil.” —Eugène Delacroix",
  "“L’art est une abstraction, c’est le moyen de monter vers Dieu en faisant comme notre divin Maître, créer.” —Paul Gauguin",
  "“Jamais personne n'a trouvé dans mes tableaux une répétition d'invention, pas même d'une main.” —Artemisia Gentileschi",
  // 10
  "“Pour créer son propre paradis, il faut puiser dans son enfer personnel.” —Frida Kahlo",
  "“Quand j’ai terminé un tableau, je ne veux pas perdre ensuite des mois entiers à le justifier devant la foule. Ce qui compte pour moi, ce n’est pas à combien de gens il plaît, mais à qui.” —Gustav Klimt",
  "“La vérité est que l'art doit être l'écriture de la vie.” —Édouard Manet",
  "“La couleur surtout et peut-être plus encore que le dessin est une libération.” —Henri Matisse",
  "“L’art naît de la contrainte et meurt dans la liberté.” —Michel-Ange",
  "“Ce que je ferai, ce sera l'impression de ce que j'aurai ressenti.” —Claude Monet",
  "“Mon ambition est de saisir une touche d'éphémère.” —Berthe Morisot",
  "“Qui voit la figure humaine correctement ? Le photographe, le miroir ou le peintre ?” —Pablo Picasso",
  "“Peignez généreusement et sans hésitations pour garder la fraîcheur de la première impression. Ne vous laissez pas intimider par la nature, au risque d’être déçu du résultat.” —Camille Pissarro",
  "“Si je veux enrichir mon esprit, je ne cherche pas les honneurs, mais la liberté.” —Rembrandt",
  // 20
  "“Un matin, l'un de nous manquant de noir, se servit de bleu : l'impressionnisme était né.” —Auguste Renoir",
  "“Il faut commencer par éprouver ce qu'on veut exprimer.” —Vincent van Gogh",
];
